"use client";

import { useState, use } from "react";
import Link from "next/link";
import { EditableVersion } from "@/components/changelog/editable-version";
import { getMockChangelog } from "@/lib/mock-data";
import type { Version, Changelog } from "@/lib/types";
import { Button } from "@/components/ui/button";
import {
  Eye,
  Save,
  Download,
  ArrowLeft,
  FileJson,
  FileText,
  ChevronDown,
  CheckCircle2,
  Sparkles,
  Undo2,
} from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

interface PageProps {
  params: Promise<{
    owner: string;
    repo: string;
  }>;
}

export default function EditPage({ params }: PageProps) {
  const { owner, repo } = use(params);

  const initialChangelog = getMockChangelog(owner, repo);
  const [changelog, setChangelog] = useState<Changelog>(initialChangelog);
  const [isSaving, setIsSaving] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [hasChanges, setHasChanges] = useState(false);

  const handleVersionUpdate = (updatedVersion: Version) => {
    setChangelog({
      ...changelog,
      versions: changelog.versions.map((v) =>
        v.id === updatedVersion.id ? updatedVersion : v,
      ),
    });
    setHasChanges(true);
    setSaveSuccess(false);
  };

  const handleSave = async () => {
    setIsSaving(true);
    await new Promise((resolve) => setTimeout(resolve, 1000));
    setIsSaving(false);
    setHasChanges(false);
    setSaveSuccess(true);
    setTimeout(() => setSaveSuccess(false), 3000);
  };

  const handleReset = () => {
    setChangelog(initialChangelog);
    setHasChanges(false);
  };

  const handleExportMarkdown = () => {
    let md = `# ${changelog.name} Changelog\n\n`;
    md += `> Generated by [logly](https://logly.app)\n\n`;
    changelog.versions.forEach((version) => {
      md += `## ${version.version} (${version.date})\n\n`;
      version.entries.forEach((entry) => {
        md += `- **${entry.type}**: ${entry.title}\n`;
        if (entry.description) {
          md += `  ${entry.description}\n`;
        }
      });
      md += "\n";
    });

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "CHANGELOG.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportJSON = () => {
    const blob = new Blob([JSON.stringify(changelog, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "changelog.json";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Editor Header */}
      <header className="border-b border-border/60 bg-background/95 backdrop-blur-sm sticky top-0 z-10">
        <div className="mx-auto max-w-3xl px-6 py-3.5">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link
                href={`/r/${owner}/${repo}`}
                className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors"
              >
                <ArrowLeft className="h-4 w-4" />
                <span className="text-sm">Back</span>
              </Link>
              <div className="h-4 w-px bg-border" />
              <div className="flex items-center gap-2">
                <span className="text-sm font-medium text-foreground">
                  {owner}/{repo}
                </span>
                {hasChanges && (
                  <span className="px-1.5 py-0.5 text-[10px] font-medium rounded bg-amber-50 text-amber-700 border border-amber-200">
                    Unsaved
                  </span>
                )}
                {saveSuccess && (
                  <span className="flex items-center gap-1 px-1.5 py-0.5 text-[10px] font-medium rounded bg-emerald-50 text-emerald-700 border border-emerald-200">
                    <CheckCircle2 className="h-3 w-3" />
                    Saved
                  </span>
                )}
              </div>
            </div>

            <div className="flex items-center gap-2">
              {hasChanges && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleReset}
                  className="text-muted-foreground"
                >
                  <Undo2 className="h-4 w-4 mr-1.5" />
                  Reset
                </Button>
              )}

              <Link href={`/r/${owner}/${repo}`}>
                <Button
                  variant="outline"
                  size="sm"
                  className="border-border/80"
                >
                  <Eye className="h-4 w-4 mr-1.5" />
                  Preview
                </Button>
              </Link>

              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-border/80"
                  >
                    <Download className="h-4 w-4 mr-1.5" />
                    Export
                    <ChevronDown className="h-3.5 w-3.5 ml-1.5 opacity-60" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="min-w-[160px]">
                  <DropdownMenuItem
                    onClick={handleExportMarkdown}
                    className="gap-2"
                  >
                    <FileText className="h-4 w-4 text-muted-foreground" />
                    <div>
                      <p className="font-medium">Markdown</p>
                      <p className="text-xs text-muted-foreground">
                        CHANGELOG.md
                      </p>
                    </div>
                  </DropdownMenuItem>
                  <DropdownMenuItem
                    onClick={handleExportJSON}
                    className="gap-2"
                  >
                    <FileJson className="h-4 w-4 text-muted-foreground" />
                    <div>
                      <p className="font-medium">JSON</p>
                      <p className="text-xs text-muted-foreground">
                        changelog.json
                      </p>
                    </div>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>

              <Button
                size="sm"
                onClick={handleSave}
                disabled={isSaving || !hasChanges}
              >
                {isSaving ? (
                  <>
                    <span className="h-4 w-4 border-2 border-background/30 border-t-background rounded-full animate-spin mr-1.5" />
                    Saving...
                  </>
                ) : (
                  <>
                    <Save className="h-4 w-4 mr-1.5" />
                    Save
                  </>
                )}
              </Button>
            </div>
          </div>
        </div>
      </header>

      {/* Editor Tips */}
      <div className="mx-auto max-w-3xl px-6 pt-8">
        <div className="flex items-start gap-3 p-4 rounded-xl bg-secondary/50 border border-border/40">
          <Sparkles className="h-5 w-5 text-muted-foreground shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-medium text-foreground">Editing mode</p>
            <p className="text-sm text-muted-foreground mt-0.5">
              Click on any text to edit. Use the regenerate button to get a new
              AI-generated description for any entry.
            </p>
          </div>
        </div>
      </div>

      <main className="mx-auto max-w-3xl px-6 py-10">
        <div className="space-y-16">
          {changelog.versions.map((version) => (
            <EditableVersion
              key={version.id}
              version={version}
              onUpdate={handleVersionUpdate}
            />
          ))}
        </div>
      </main>

      {/* Floating save bar when there are changes */}
      {hasChanges && (
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-20">
          <div className="flex items-center gap-3 px-4 py-2.5 bg-foreground text-background rounded-full shadow-lg">
            <span className="text-sm">You have unsaved changes</span>
            <Button
              size="sm"
              variant="secondary"
              onClick={handleSave}
              disabled={isSaving}
              className="h-7 px-3 text-xs bg-background text-foreground hover:bg-background/90"
            >
              {isSaving ? "Saving..." : "Save now"}
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
